# Generated by Django 4.2.4 on 2023-09-01 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_no',
        ),
    ]
