# Generated by Django 4.2.4 on 2023-09-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_leave_status_alter_login_login_password_leave_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave_apply',
            name='status',
        ),
        migrations.AlterField(
            model_name='leave_apply',
            name='leave_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leave_apply',
            name='reason',
            field=models.TextField(max_length=50),
        ),
    ]
